### ISSUE TITLE
clamp 1.3.0 default_XXX method behavior breaking fpm

### ISSUE THREAD

**Issue by mrtazz** [jordansissel/fpm#1543]
It seems like clamp's new behavior for default methods (introduced in https://github.com/mdub/clamp/commit/ec192bf677ea518299dc16bf6733c00837a83b58 and released with version 1.3.0) breaks fpm with the following error:

```
/usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x000000080462f870> (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:403:in `execute'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:575:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

**Comment by jordansissel** [comment]
Can you show me how to reproduce this error?

If I test ruby 2.5.1p57 with rubygems 2.7.6, `gem install fpm` installs `clamp 1.0.1`:

```
% gem install fpm
Fetching: clamp-1.0.1.gem (100%)
Successfully installed clamp-1.0.1
Fetching: fpm-1.10.2.gem (100%)
Successfully installed fpm-1.10.2
2 gems installed
```

Did rubygems behavior of `~>` change recently to cause `1.3.0` to selected instead?

**Comment by mrtazz** [comment]
I'll try to see how I got to this error. Now that I think about it again there is a decent chance that this is more a bug with the [FreeBSD port](https://www.freshports.org/archivers/rubygem-fpm/) as it doesn't specify this tight of a dependency and has the newer clamp gem in the tree.

**Comment by jordansissel** [comment]
@kovetskiy good enough for me. I'll try to figure out why clamp 1.3.0 is giving fpm issues.

**Comment by jordansissel** [comment]
I am able to reproduce an error with clamp 1.3.0:

```
% bundle exec bin/fpm  -s gem -t deb rails
bundler: failed to load command: bin/fpm (bin/fpm)
NoMethodError: undefined method `default_architecture' for #<FPM::Command:0x005579fa0ff3b0>
Did you mean?  default_attrs
  /home/jls/projects/fpm/lib/fpm/command.rb:397:in `block in execute'
  /home/jls/projects/fpm/lib/fpm/command.rb:402:in `execute'
  /home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
  /home/jls/projects/fpm/lib/fpm/command.rb:574:in `run'
  /home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
  bin/fpm:7:in `<top (required)>'
```

I'll see about fixing this.

**Comment by jordansissel** [comment]
I think I have a fix for this and thankfully it's just one line (so far). I'll do some testing on clamp 1.3.0 and <1.3.0 and push a PR shortly.

**Comment by jordansissel** [comment]
https://github.com/jordansissel/fpm/pull/1561 should fix this. Can someone help test?

**Comment by rcsavage** [comment]
This issue still persists, can we get the PR accepted?

**Comment by rcsavage** [comment]
See

~/dvn-personal/dvn-kubernetes/rpm/rpmpackageroot (dev/engineering ✘)✖✭ ᐅ fpm --rpm-os linux -a native -s dir -t rpm -n "kubelet" -v 1.12.2 -C . --iteration dvn
/Library/Ruby/Gems/2.3.0/gems/fpm-1.10.2/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x00007fb8df187eb0> (NoMethodError)
Did you mean?  default_attrs
	from /Library/Ruby/Gems/2.3.0/gems/fpm-1.10.2/lib/fpm/command.rb:402:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
	from /usr/local/bin/fpm:22:in `load'
	from /usr/local/bin/fpm:22:in `<main>'
~/dvn-personal/dvn-kubernetes/rpm/rpmpackageroot (dev/engineering ✘)✖✭ ᐅ sudo vim /Library/Ruby/Gems/2.3.0/gems/fpm-1.10.2/lib/fpm/command.rb
~/dvn-personal/dvn-kubernetes/rpm/rpmpackageroot (dev/engineering ✘)✖✭ ᐅ sudo gem uninstall gem uninstall
~/dvn-personal/dvn-kubernetes/rpm/rpmpackageroot (dev/engineering ✘)✖✭ ᐅ sudo gem uninstall clamp --version 1.3.0
Successfully uninstalled clamp-1.3.0
~/dvn-personal/dvn-kubernetes/rpm/rpmpackageroot (dev/engineering ✘)✖✭ ᐅ fpm --rpm-os linux -a all -s dir -t rpm -n "kubelet" -v 1.12.2 -C . --iteration dvn
Created package {:path=>"kubelet-1.12.2-dvn.noarch.rpm"}

**Comment by bedge** [comment]
This is still broken?
```
/Library/Ruby/Gems/2.3.0/gems/fpm-1.11.0/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x00007fe839979d88> (NoMethodError)
        from /Library/Ruby/Gems/2.3.0/gems/fpm-1.11.0/lib/fpm/command.rb:402:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fpm-1.11.0/lib/fpm/command.rb:574:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/fpm-1.11.0/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:22:in `load'
        from /usr/local/bin/fpm:22:in `<main>'
make: *** [jboss] Error 1


❯ fpm --version
1.11.0

❯ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

❯ gem list | grep clamp
clamp (1.0.1)

❯ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/bedge/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/bedge/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/bedge/.rbenv/versions/2.6.3/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/bedge/.rbenv/versions/2.6.3/bin
  - SPEC CACHE DIRECTORY: /Users/bedge/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/bedge/.rbenv/versions/2.6.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/bedge/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
     - /Users/bedge/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/bedge/.rbenv/versions/2.6.3/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /usr/local/Cellar/zplug/2.4.2/bin
     - /Users/bedge/.zplug/bin
     - /usr/local/Cellar/pyenv-virtualenv/1.1.3/shims
     - /Users/bedge/.pyenv/shims
     - /Users/bedge/.jenv/shims
     - /Users/bedge/.bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/local/opt/curl/bin
     - /usr/local/opt/gnu-sed/bin
     - /usr/local/opt/gnu-tar/libexec/gnubin
     - /usr/local/opt/coreutils/libexec/gnubin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

**Comment by chnrxn** [comment]
It's getting close to a year since this issue was found. It definitely is a blocker for me. Any chance this can get fixed soon?

**Comment by kovetskiy** [comment]
@chnrxn yes, here is the fix but it was rejected: https://github.com/jordansissel/fpm/pull/1548

**Comment by jordansissel** [comment]
#1561 should fix this, but one report says it Broke things... can someone
else help test it?

**Comment by jkugler** [comment]
Just FYI, I was able to use FPM by applying this patch to the gemspec:
```
--- fpm.gemspec.original	2019-11-07 18:32:32.051393000 -0800
+++ fpm.gemspec	2019-11-07 18:33:00.941454000 -0800
@@ -39,7 +39,7 @@

   # For command-line flag support
   # https://github.com/mdub/clamp/blob/master/README.markdown
-  spec.add_dependency("clamp", "~> 1.0.0") # license: MIT
+  spec.add_dependency("clamp", "~> 1.2.0") # license: MIT
```
It produced a valid package, and the package passed my tests. This of course restricted it to `clamp < 1.3`.

**Comment by jcbollinger** [comment]
#1561 fixed the issue for me in FPM 1.11.0, with Clamp 1.3.1.  I did not see any adverse effects (that I recognized) with a dir source and an rpm target.

**Comment by jordansissel** [comment]
#1561 was merged and this fix will be available in the next release of fpm.

**Comment by tylarb** [comment]
@jordansissel   any ETA on a new release? it looks like the most recent one is over a year old now, and this bug still exists...
