### ISSUE TITLE
safesystemout doesn't work in jruby 1.7.18 (newest version)

### ISSUE THREAD

**Issue by djhaskin987** [jordansissel/fpm#832]
Steps to reproduce:
1. Start from the root directory of fpm.
2. Run these commands.
```
$ /opt/jruby-1.7.18/bin/irb
> require "fpm"
> include FPM::Util
> safesystemout("gem env")
irb(main):004:0> safesystemout("gem env")
safesystemout("gem env")
NoMethodError: undefined method `debug' for nil:NilClass
	from /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/util.rb:98:in `safesystemout'
	from (irb):4:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /opt/StorageCraft/stc-jruby-1.7.16/bin/irb:13:in `(root)'
```

I cannot reproduce this error using the de-facto ruby.
This is because it can't find the variable `logger` in jruby. I don't know why, but because of it I can't build any rpm's out of gems using jruby, which is by far my preferred method.

**Comment by djhaskin987** [comment]
Here is the output I get when I try to make a gem:
```
/opt/jruby-1.7.16/bin/jruby --debug -S fpm -s gem -t deb nokogiri
<rageCraft/stc-jruby-1.7.16/bin/jruby --debug -S fpm -s gem -t deb nokogiri
NoMethodError: undefined method `split' for nil:NilClass
  install_to_staging at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/package/gem.rb:190
               input at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/package/gem.rb:56
             execute at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/command.rb:302
                each at org/jruby/RubyArray.java:1613
             execute at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/command.rb:301
                 run at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/clamp-0.6.3/lib/clamp/command.rb:67
                 run at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/lib/fpm/command.rb:482
                 run at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/clamp-0.6.3/lib/clamp/command.rb:125
              (root) at /opt/jruby-1.7.16/lib/ruby/gems/shared/gems/fpm-1.2.0/bin/fpm:8
                load at org/jruby/RubyKernel.java:1081
              (root) at /opt/jruby-1.7.16/bin/fpm:1
```
I get the same output from jruby 1.7.18 .

**Comment by djhaskin987** [comment]
> > NoMethodError: undefined method `debug' for nil:NilClass

> This occurs because it's looking for @logger. This only occurs in your irb session.


It only occurs in my irb session *when I'm using jruby*. When I'm using MRI, those commands just work. Thanks for taking a look!
