### ISSUE TITLE
New version of cabin conflicts with FPM

### ISSUE THREAD

**Issue by mrochford** [jordansissel/fpm#1051]
A new version of cabin was release 2015/12/16. It produces the following error when running fpm

```ruby
/usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included': undefined method `options' for #<Cabin::Subscriber:0x2b712a9f6f98> (NoMethodError)
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/gems/1.8/gems/backports-3.6.7/lib/backports/tools/path.rb:24:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:94:in `log'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:484:in `execute'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
	from /usr/bin/fpm:19:in `load'
	from /usr/bin/fpm:19
```

**Comment by jordansissel** [comment]
Oops, good catch! I will fix this shortly.

**Comment by jordansissel** [comment]
Hmm, I can't reproduce. Can you show me your command line?

This works for me without error w/ cabin 0.8.0:

```
% fpm -s empty -t rpm -n foo
no value for epoch is set, defaulting to nil {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
Created package {:path=>"foo-1.0-1.x86_64.rpm"}
```

(fpm 1.4.0, cabin 0.8.0)

**Comment by jordansissel** [comment]
In addition to your fpm invocation, can you also tell me what version of ruby?

**Comment by mrochford** [comment]
Weird.  I am sure my ruby is old. 

server: / # ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
server :/ #

**Comment by mrochford** [comment]
Here is what I am running. 

/usr/bin/fpm -s dir -t rpm -n python --version ${pythonver} --epoch 0 --iteration $(build_date) --license 'LIC'  --description "Custom compile of python"  --rpm-user <someuser> --rpm-group <somesuers -p ./RPMs/ /data/python /etc/profile.d/python.sh

**Comment by thefosk** [comment]
Same happens to me:

```
[root@ba0ca28601ab /]# fpm
/usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included': undefined method `options' for #<Cabin::Subscriber:0x7efda9bd40e0> (NoMethodError)
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:90:in `log_with_level'
	from /usr/lib/ruby/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:75:in `warn'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:294:in `execute'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:293:in `each'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:293:in `execute'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
	from /usr/bin/fpm:19:in `load'
	from /usr/bin/fpm:19
[root@ba0ca28601ab /]# ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
```

**Comment by jsvd** [comment]
Confirmed this is an issue with ruby 1.8, as it works with ruby MRI 2.2 and jruby 1.7 (ruby 1.9):

```ruby
2.2.1 :001 > require 'cabin'
2.2.1 :002 > c = Cabin::Channel.new
2.2.1 :003 > c.subscribe STDOUT
2.2.1 :004 > c.warn "test"
test {:level=>:warn}
```

but fails with ruby 1.8:

```ruby
1.8.7-p374 :001 > require 'rubygems'
1.8.7-p374 :002 > require 'cabin'
1.8.7-p374 :003 > c = Cabin::Channel.new
1.8.7-p374 :004 > c.subscribe STDOUT
1.8.7-p374 :005 > c.warn "meh"
NoMethodError: undefined method `options' for #<Cabin::Subscriber:0x101c92730>
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from (irb):7:in `all?'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:90:in `log_with_level'
	from /Users/joaoduarte/.rvm/gems/ruby-1.8.7-p374/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:75:in `warn'
	from (irb):7
```

**Comment by triplepoint** [comment]
can confirm, we're seeing the same issue:
```
gem list

*** LOCAL GEMS ***

arr-pm (0.0.10)
backports (3.6.7)
cabin (0.8.0)
childprocess (0.5.8)
clamp (0.6.5)
ffi (1.9.10)
fpm (1.3.3)
json (1.8.3)
```

```
 ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-linux]
```

```
$ fpm`
/var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:12:in `included': undefined method `options' for #<Cabin::Subscriber:0xb705ff20> (NoMethodError)
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `call'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `all?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `each'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `all?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:105:in `allow_event?'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:195:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `each'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:193:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `synchronize'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/channel.rb:192:in `publish'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:113:in `_log'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:90:in `log_with_level'
	from /var/lib/gems/1.8/gems/cabin-0.8.0/lib/cabin/mixins/logger.rb:75:in `warn'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:285:in `execute'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:284:in `each'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:284:in `execute'
	from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
	from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/1.8/gems/fpm-1.3.3/bin/fpm:8
	from /usr/local/bin/fpm:19:in `load'
	from /usr/local/bin/fpm:19
```

This was on a pretty much stock Ubuntu Precise 32-bit virtualbox instance.

**Comment by nhorvath** [comment]
A workaround for this is to "gem uninstall cabin" (say yes to everything) and "gem install cabin -v 0.7.2". I was having the same error message with ruby 1.8.7 and manually installing the last version of cabin resolved the issue.

**Comment by rbrasga** [comment]
Also experienced this error in CentOS 6.x:

    $ yum install ruby-devel gcc rubygems-1.3.7-5.el6.noarch -y
    $ gem install fpm
    $ fpm -s python -t rpm     -d python-setuptools     -d Django -d django-tagging     -d python-devel     -d python-twisted     -d python-memcached     -d python-sqlite2     -d bitmap -d bitmap-console-fonts -d bitmap-fixed-fonts -d bitmap-fonts-compat     -d bitmap-lucida-typewriter-fonts -d bitmap-miscfixed-fonts     -d pycairo     carbon

**The workaround from @nhorvath resolved the issue for me! Thank you!!**

**Comment by josephfrazier** [comment]
I also encountered this and was able to use @nhorvath's workaround.

**Comment by albertux** [comment]
Same here +1 @nhorvath uninstall and install old cabin works for me too

**Comment by slashnull** [comment]
I notice this is closed.  Does this mean it will never be fixed.  The work around works perfectly well, but should I be changing all of my scripts to include it or will it get fixed eventually?

**Comment by slashnull** [comment]
Also experienced this error in CentOS 6.5
The workaround from @nhorvath resolved the issue for me.

**Comment by rbrasga** [comment]
I am not able to compile FPM, but I would imagine changing line 27 in “fpm.gemspec” could resolve the issue:


Ø  Current:

o   spec.add_dependency("cabin", ">= 0.6.0") # license: Apache 2


Ø  Recommended:

o   spec.add_dependency("cabin", "0.7.2") # license: Apache 2

Thanks,
-Remi

**Comment by rbrasga** [comment]
I am not able to compile FPM, but I would imagine changing line 27 in “fpm.gemspec” could resolve the issue:

	Current:
o	spec.add_dependency("cabin", ">= 0.6.0") # license: Apache 2

	Recommended:
o	spec.add_dependency("cabin", "0.7.2") # license: Apache 2

**Comment by jordansissel** [comment]
I'll fix this as soon as I am able to, but for now I hope the work around is good for folks.

Sorry for the delays...

**Comment by jsvd** [comment]
ruby-cabin 0.8.1 has been published to fix ruby 1.8 compatiblity (see more at https://github.com/jordansissel/ruby-cabin/issues/41)
