### PR TITLE
fix clamp gem as < 1.3.0 (fix #1543)

### LINKED ISSUE #1543: clamp 1.3.0 default_XXX method behavior breaking fpm
It seems like clamp's new behavior for default methods (introduced in https://github.com/mdub/clamp/commit/ec192bf677ea518299dc16bf6733c00837a83b58 and released with version 1.3.0) breaks fpm with the following error:

```
/usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x000000080462f870> (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:403:in `execute'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:575:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by kovetskiy**

### CODE REVIEW

**Comment by jordansissel** [comment]
Thank you for this patch :)

I would rather make fpm work against clamp 1.3.0 rather than pin lower versions. I'll try and get to this soon.

**Comment by jordansissel** [comment]
#1561 should fix this issue without requiring an older version of clamp. Any testing of #1561 is very welcome.

I appreciate your efforts to improve fpm very much :)
