### PR TITLE
Check if an option has a default value before we try to look it up.

### LINKED ISSUE #1543: clamp 1.3.0 default_XXX method behavior breaking fpm
It seems like clamp's new behavior for default methods (introduced in https://github.com/mdub/clamp/commit/ec192bf677ea518299dc16bf6733c00837a83b58 and released with version 1.3.0) breaks fpm with the following error:

```
/usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:397:in `block in execute': undefined method `default_architecture' for #<FPM::Command:0x000000080462f870> (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:403:in `execute'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/lib/fpm/command.rb:575:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by jordansissel**
This fixes fpm when used with clamp 1.3.0 or above.

Fixes #1543

### CODE REVIEW

**Comment by chnrxn** [comment]
Why has the build failed?

**Comment by chnrxn** [comment]
I have manually applied this fix on fpm-1.9.3 and have verified this fix to work. Please integrate this.

**Comment by Apteryks** [comment]
@jordansissel I've tested this and it seems to work fine for me (clamp is at 1.3.2).

**Comment by jordansissel** [comment]
@Apteryks Thank you for testing :)

**Comment by mkurz** [comment]
Any chance for a new release with this fix?
