### ISSUE TITLE
fix regression in commit e7a9db50d45d149f34fd9913f688a77eb89721a4

### ISSUE THREAD

**Issue by PiskarevSA** [jordansissel/fpm#1683]
/usr/local/share/gems/gems/fpm-1.11.0/lib/fpm/package/rpm.rb:312:in `block in converted_from': undefined local variable or method `script_errors' for #<FPM::Package::RPM:0x000000032c77b8> (NameError)
