### ISSUE TITLE
RPM triggers code produces exception: undefined method for nil:NilClass

### ISSUE THREAD

**Issue by xelwarto** [jordansissel/fpm#801]
Changes introduced in https://github.com/jordansissel/fpm/pull/626 have rendered general RPM input non-functional.

``` ruby
val = tags[:triggerindex].zip(tags[:triggername],tags[:triggerflags],tags[:triggerversion]).group_by{ |x| x[0]}
```

This line raises the following error when attempting to input a localized RPM:

```
undefined method `zip' for nil:NilClass
```

The code should NOT assume that all RPM files will have a trigger.
